[package]
name = "sparse_solver"
version = "0.1.0"
authors = ["Gu Junhua <jhgu@nao.cas.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = '0.13.0'
num-traits = '0.2.8'
sprs = '0.6.5'
