[dependencies]
ndarray = '0.13.0'
num-complex = '0.2.4'
num-traits = '0.2.11'
sprs = '0.7.1'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'linear_solver'
version = '0.1.0'
